baseURL ="https://bloodymoonpirate.github.io/"

languageCode = 'en-us'
title = 'Quantitative Poetry'
theme = "texify"
licenselink = "https://github.com/francescotonini/texify/blob/master/LICENSE"
description = "A minimal, latex-style hugo theme for personal blogging"
homepage = "https://bloodymoonpirate.github.io/home"
tags = ["blog", "clean", "latex", "light", "minimal", "responsive", "simple"]
features = ["blog"]
min_version = "0.60"
[params]
  mainSections = ["posts"]
[author]
  name = "Charaf ZGUIOUAR"
  homepage = ""

relativeURLs = true
canonifyURLs = true
